import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header className="header">
          <div className="navBar">
            <Link href='/'>Home</Link>
            <Link href='/members'>Members</Link>
            <Link href='/bbs'>Board</Link>
          </div>
          <div className="fr">
            <Link href="/members/login">Login</Link>
            <Link href="/members/signup">Signup</Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
